name: campusassistant
description: stay connected

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^1.16.0
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  firebase_storage: ^10.2.15
#  firebase_messaging: ^11.4.1
  firebase_analytics: ^9.1.9

  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  file_picker: ^4.5.1
  open_file: ^3.2.1
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3

  dio: ^4.0.6
  url_launcher: ^6.1.1
  multi_select_flutter: ^4.1.2
  share_plus: ^4.0.4

  provider: ^6.0.2
  uuid: ^3.0.6

  youtube_player_flutter: ^8.1.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
#  flutter_local_notifications: ^9.6.1
  http: ^0.13.4
  url_strategy: ^0.2.0
  syncfusion_flutter_pdfviewer: ^20.1.61-beta




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf

























